spring:
 datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: sa
   password: '{cipher}bfd1ace86e56fe77030e2f6f998c4f283ebe2db1d6c436b1f5d34ebc593c3a44'

token:
  expiration_time: 86400000 # 하루 60*60*24*1000
  secret: user_token_#3 # 임의값
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.